from django.urls import path
from.import views

urlpatterns = [
    path('', views.index, name='index'),
    path('Home', views.index, name='index'),
    path('login_in',views.login_in,name='login_in'),
    path('Login_Res',views.Login_Res),
    path('Logout_Window',views.Logout_Window),
    path('add_customers',views.add_customers),
    path('customer_view', views.customer_view),
    path('customers_details', views.customers_details),
    path('add_lineworkers', views.add_lineworkers),
    path('lineworkers_details', views.lineworkers_details),
    path('cus_reg_submit',views.cus_reg_submit),
    path('line_reg_submit',views.line_reg_submit),
    path('Password_window',views.Password_window),
    path('customer_contact', views.customer_contact),
    path('admin_plan_reg',views.admin_plan_reg),
    path('admin_plan_res',views.admin_plan_res),
    path('admin_plan_view', views.admin_plan_view),
    path('admin_plan_update', views.admin_plan_update),
    path('admin_plan_updated_res', views.admin_plan_updated_res),
    path('customer_profile',views.customer_profile),
    path('worker_profile', views.worker_profile),
    path('customer_delete', views.customer_delete),
    path('Dashboard', views.Dashboard),
    path('Admin_page',views.Admin_page),
    path('Admin_oldpswd',views.Admin_oldpswd),
    path('request_form',views.request_form),
    path('requst_res',views.requst_res),
    path('request_submit',views.request_submit),
    path('worker_inbox',views.worker_inbox),
    path('customer_inform',views.customer_inform),
    path('inform_submit',views.inform_submit),
    path('complaints',views.complaints),
    path('worker_plan_view',views.worker_plan_view),
    path('lineworker_page',views.lineworker_page),
    path("customer_plan_view",views.customer_plan_view),
    path('Customer_page',views.lineworker_page),
    path('About',views.About),
]
